### ISSUE TITLE
some of the examples not working?

### ISSUE THREAD

**Issue by kcallahan** [swilliams/jq-wysihat#3]
Hey There,

Looking at this and it's so promising. However, some of the examples don't work, and I've been patching them as I find the issues (wrong path to js lib, incorrect parameters passed in, etc).

Happy to submit my changes if you're interested. Excited to see a jquery-based editor solution that isn't a bloated hack :)

Thanks,

-kevin

**Comment by swilliams** [comment]
Hi Kevin,

As I was porting wysihat, I kind of let the examples get out of sync, since I was in a rush. I would love it if you submitted a pull request!

-Scott

**Comment by kcallahan** [comment]
Looks like Kevin Davis took care of these and got a pull request set up. I'll wait until you get that merged and do a pull/diff against my code...

-kevin
