### ISSUE TITLE
Not saving to database

### ISSUE THREAD

**Issue by docgecko** [swilliams/jq-wysihat#9]
I have a form for creating new and editing existing records.  On the form I have added the text_area, with id => :description.  I've associated this text_area to Wysihat, and as such it is being hidden by Wysihat and an editor text_area appears instead, which I believe is correct, right?

So I was wondering how the editor text_area is used to update the database when the record is saved, and how the editor text_area is filled with data when I next come to edit it.  Is the editor text_area supposed to update the text_area (id => :description), that then sends the data to the hash, before saving to the database?

At the moment, my data is only going into text_area (id => :description), and thus can not be seen or edited.

Many thanks for your help!

D.

**Comment by swilliams** [comment]
The simplest way is to just copy the html of the editor back to the textarea before the form is submitted:

```
$('form#myform').submit(function() {
     $('#my_textarea').val($('#editor').html());
});
```

This question pops up a lot, I should probably make a wiki page on it :)

**Comment by docgecko** [comment]
Cool, thats worked just fine, thanks.

Also, if you go back to the form to edit, then I used the following to get the data from the model and pass it to the editor, in order to view and edit the data:

``` javascript
$('form#myform').ready(function() {
    $('#my_editor.editor').html("#{escape_javascript @model.field}");
});
```

In this case:
1. I take the data direct from the model, hence the @model.field, and
2. I am also using haml, hence the #{escape_javascript ??}

The ready function allows the editor to be updated once the page has fully loaded and I used data direct from the model as I could not get it to work by taking the data from the text_area#content and passing to the editor.  I don't know why I could not get that to work.

Anyway, thanks for your help.  And yes, a wiki page would be very helpful, and if I can help, please let me know.
